-- Recovery-infrastructure demo seed (additive; runs after 0003).
-- Everything here is ILLUSTRATIVE DEMO DATA for the fictional Cedar Ridge company.

INSERT INTO company_settings (company_id, region, currency, date_format, retention_days, data_source, created_at, updated_at) VALUES
('cmp_1000', 'us', 'USD', 'MDY', 365, 'Demonstration dataset for Cedar Ridge Heating & Cooling (fictional)', datetime('now'), datetime('now'));

-- job types on a few leads (HVAC-specific classification)
UPDATE leads SET job_type = 'furnace_repair'      WHERE id = 'ldg_n4';
UPDATE leads SET job_type = 'ac_repair'           WHERE id = 'ldg_n2';
UPDATE leads SET job_type = 'installation'        WHERE id = 'ldg_e2';
UPDATE leads SET job_type = 'ductless_install'    WHERE id = 'ldg_e1';
UPDATE leads SET job_type = 'heat_pump'           WHERE id = 'ldg_q2';
UPDATE leads SET job_type = 'boiler'              WHERE id = 'ldg_d1';

-- quote pipeline state on open estimates
UPDATE estimates SET quote_status = 'followup_due', recovery_priority = 'high',   last_contact_at = datetime('now','-11 days') WHERE id = 'est_1002';
UPDATE estimates SET quote_status = 'no_response',  recovery_priority = 'high',   last_contact_at = datetime('now','-9 days')  WHERE id = 'est_1001';
UPDATE estimates SET quote_status = 'sent',         recovery_priority = 'medium', last_contact_at = datetime('now','-5 days')  WHERE id = 'est_1003';
UPDATE estimates SET quote_status = 'booked',       recovery_priority = 'low'                                  WHERE id = 'est_1004';

-- ============ ENQUIRIES (last 90 days — powers Response Health) ============
INSERT INTO enquiries (id, company_id, lead_id, contact_name, contact_phone, contact_email, channel, received_at, first_response_at, response_minutes, urgency, job_type, estimated_value, outcome, created_at, updated_at) VALUES
('enq_7001','cmp_1000','ldg_n1','Angela Brooks','(918) 555-0137','angela.brooks@example.com','web_form', datetime('now','-5 days','+10 hours'), datetime('now','-5 days','+14 hours'), 240, 'normal','duct_sealing', 3400, 'open_lead', datetime('now','-5 days'), datetime('now','-5 days')),
('enq_7002','cmp_1000','ldg_n2','Tom Garrison','(918) 555-0189','tgarrison@example.com','google_ads', datetime('now','-3 days','+15 hours'), datetime('now','-3 days','+19 hours'), 265, 'urgent','ac_repair', 8900, 'open_lead', datetime('now','-3 days'), datetime('now','-3 days')),
('enq_7003','cmp_1000','ldg_n3','Lisa Nguyen','(918) 555-0126','lisa.nguyen@example.com','facebook', datetime('now','-2 days','+11 hours'), datetime('now','-2 days','+12 hours'), 75, 'normal','thermostat', 1150, 'open_lead', datetime('now','-2 days'), datetime('now','-2 days')),
('enq_7004','cmp_1000','ldg_w2','Robert Hayes','(918) 555-0121','rhayes@example.com','phone', datetime('now','-16 days','+16 hours'), NULL, NULL, 'high','furnace_replacement', 11200, 'missed_then_recovered', datetime('now','-16 days'), datetime('now','-6 days')),
('enq_7005','cmp_1000',NULL,'Irene Castillo','(918) 555-0151',NULL,'phone', datetime('now','-6 days','+20 hours'), NULL, NULL, 'high','furnace_repair', 4800, 'no_response', datetime('now','-6 days'), datetime('now','-6 days')),
('enq_7006','cmp_1000',NULL,'Walt Jennings','(918) 555-0131',NULL,'phone', datetime('now','-4 days','+9 hours'), NULL, NULL, 'normal','ac_repair', 4800, 'no_response', datetime('now','-4 days'), datetime('now','-4 days')),
('enq_7007','cmp_1000',NULL,'Pamela Rhodes','(918) 555-0106',NULL,'phone', datetime('now','-2 days','+17 hours'), NULL, NULL, 'normal','maintenance', 4800, 'no_response', datetime('now','-2 days'), datetime('now','-2 days')),
('enq_7008','cmp_1000',NULL,'Marcus Webb','(918) 555-0146',NULL,'email', datetime('now','-8 days','+13 hours'), datetime('now','-8 days','+18 hours'), 300, 'normal','duct_repair', 2200, 'open_lead', datetime('now','-8 days'), datetime('now','-8 days')),
('enq_7009','cmp_1000',NULL,'Dana Whitmore','(918) 555-0172',NULL,'web_form', datetime('now','-12 days','+10 hours'), datetime('now','-12 days','+11 hours'), 55, 'normal','heat_pump', 6400, 'booked', datetime('now','-12 days'), datetime('now','-11 days')),
('enq_7010','cmp_1000',NULL,'Felix Ortega','(918) 555-0188',NULL,'phone', datetime('now','-15 days','+14 hours'), datetime('now','-15 days','+14 hours'), 4, 'urgent','furnace_repair', 3900, 'booked', datetime('now','-15 days'), datetime('now','-15 days')),
('enq_7011','cmp_1000',NULL,'June Castellanos','(918) 555-0104',NULL,'web_form', datetime('now','-18 days','+9 hours'), datetime('now','-18 days','+10 hours'), 35, 'normal','maintenance', 890, 'booked', datetime('now','-18 days'), datetime('now','-17 days')),
('enq_7012','cmp_1000',NULL,'Alma Petty','(918) 555-0158',NULL,'google_ads', datetime('now','-21 days','+16 hours'), datetime('now','-21 days','+16 hours'), 8, 'high','ac_repair', 5200, 'booked', datetime('now','-21 days'), datetime('now','-20 days')),
('enq_7013','cmp_1000',NULL,'Silas Ford','(918) 555-0133',NULL,'phone', datetime('now','-24 days','+11 hours'), datetime('now','-24 days','+13 hours'), 95, 'normal','thermostat', 1400, 'booked', datetime('now','-24 days'), datetime('now','-23 days')),
('enq_7014','cmp_1000',NULL,'Rosa Delacroix','(918) 555-0129',NULL,'web_form', datetime('now','-27 days','+15 hours'), datetime('now','-27 days','+17 hours'), 130, 'normal','duct_repair', 3100, 'booked', datetime('now','-27 days'), datetime('now','-26 days')),
('enq_7015','cmp_1000',NULL,'Otis Granger','(918) 555-0169',NULL,'email', datetime('now','-31 days','+10 hours'), datetime('now','-31 days','+15 hours'), 290, 'low','maintenance', 890, 'booked', datetime('now','-31 days'), datetime('now','-30 days')),
('enq_7016','cmp_1000',NULL,'Nina Vasquez','(918) 555-0176',NULL,'facebook', datetime('now','-34 days','+13 hours'), datetime('now','-34 days','+13 hours'), 12, 'normal','mini_split', 4800, 'booked', datetime('now','-34 days'), datetime('now','-33 days')),
('enq_7017','cmp_1000',NULL,'Clyde Barrow','(918) 555-0108',NULL,'phone', datetime('now','-38 days','+9 hours'), datetime('now','-38 days','+11 hours'), 140, 'normal','furnace_repair', 2600, 'booked', datetime('now','-38 days'), datetime('now','-37 days')),
('enq_7018','cmp_1000',NULL,'Greta Lindqvist','(918) 555-0184',NULL,'web_form', datetime('now','-42 days','+14 hours'), datetime('now','-42 days','+14 hours'), 22, 'high','heat_pump', 7600, 'booked', datetime('now','-42 days'), datetime('now','-41 days')),
('enq_7019','cmp_1000',NULL,'Hank Morrow','(918) 555-0116',NULL,'google_ads', datetime('now','-46 days','+10 hours'), datetime('now','-46 days','+12 hours'), 120, 'normal','furnace_replacement', 6800, 'booked', datetime('now','-46 days'), datetime('now','-45 days')),
('enq_7020','cmp_1000',NULL,'Bea Sullivan','(918) 555-0141',NULL,'phone', datetime('now','-52 days','+16 hours'), datetime('now','-52 days','+16 hours'), 6, 'urgent','ac_repair', 4400, 'booked', datetime('now','-52 days'), datetime('now','-51 days')),
('enq_7021','cmp_1000',NULL,'Lowell Tracey','(918) 555-0124',NULL,'web_form', datetime('now','-58 days','+11 hours'), datetime('now','-58 days','+13 hours'), 115, 'normal','duct_sealing', 2900, 'booked', datetime('now','-58 days'), datetime('now','-57 days')),
('enq_7022','cmp_1000',NULL,'Fay Obrien','(918) 555-0154',NULL,'email', datetime('now','-64 days','+9 hours'), datetime('now','-64 days','+10 hours'), 45, 'normal','maintenance', 890, 'booked', datetime('now','-64 days'), datetime('now','-63 days')),
('enq_7023','cmp_1000',NULL,'Gus Feldman','(918) 555-0138',NULL,'phone', datetime('now','-71 days','+15 hours'), datetime('now','-71 days','+15 hours'), 18, 'normal','furnace_repair', 3300, 'booked', datetime('now','-71 days'), datetime('now','-70 days')),
('enq_7024','cmp_1000',NULL,'Ida Pemberton','(918) 555-0179',NULL,'web_form', datetime('now','-79 days','+10 hours'), datetime('now','-79 days','+12 hours'), 110, 'normal','thermostat', 1250, 'booked', datetime('now','-79 days'), datetime('now','-78 days')),
('enq_7025','cmp_1000',NULL,'Reed Ashford','(918) 555-0191',NULL,'google_ads', datetime('now','-86 days','+14 hours'), datetime('now','-86 days','+14 hours'), 9, 'high','ac_repair', 5600, 'booked', datetime('now','-86 days'), datetime('now','-85 days'));

-- ============ RECOVERY OPPORTUNITIES (unified pipeline) ============
-- Open opportunities — the working queue
INSERT INTO recovery_opportunities (id, company_id, source_type, source_id, lead_id, customer_name, job_type, category, title, why, recommended_action, estimated_value, stage, priority, owner, age_days, last_event_at, created_at, updated_at) VALUES
('rop_8001','cmp_1000','quote','est_1002','ldg_e2','Mike Thompson','installation','Quote follow-up','$7,200 furnace estimate — no reply in 7 days','Quote sent 7 days ago. No recorded follow-up. Customer opened the email twice but never replied.','Call today — confirm receipt, answer questions, offer to walk through line items.',7200,'identified','high','office',7, datetime('now','-7 days'), datetime('now','-7 days'), datetime('now','-1 day')),
('rop_8002','cmp_1000','missed_call','mcl_4004','ldg_n4','Harold Kim','furnace_repair','Missed enquiry','Missed call — furnace ignition out, no contact yet','High-intent caller reached voicemail at 4:52pm. No contact recorded since.','Call back within 4 business hours. Offer same-week diagnostic.',4800,'identified','high','owner',1, datetime('now','-1 day'), datetime('now','-1 day'), datetime('now','-1 day')),
('rop_8003','cmp_1000','missed_call','mcl_4005',NULL,'Pamela Rhodes','maintenance','Missed enquiry','Missed call — no voicemail, no lead created','Caller never reached anyone. No record of a call-back.','Call back today and qualify the request.',4800,'identified','high','owner',2, datetime('now','-2 days'), datetime('now','-2 days'), datetime('now','-2 days')),
('rop_8004','cmp_1000','missed_call','mcl_4006',NULL,'Walt Jennings','ac_repair','Missed enquiry','Missed call — called twice, still unrecovered','Two calls in one week. Without contact he likely booked a competitor.','Call, apologise for the delay, offer priority slot.',4800,'identified','high','owner',4, datetime('now','-4 days'), datetime('now','-4 days'), datetime('now','-4 days')),
('rop_8005','cmp_1000','quote','est_1001','ldg_e1','James Whitfield','ductless_install','Quote follow-up','$9,800 ductless estimate — 9 days silent','Quote sent 9 days ago. No recorded follow-up. Not marked lost.','Call with a seasonal-slot offer; follow with an email recap.',9800,'identified','high','office',9, datetime('now','-9 days'), datetime('now','-9 days'), datetime('now','-1 day')),
('rop_8006','cmp_1000','slow_response','enq_7001','ldg_n1','Angela Brooks','duct_sealing','Slow response','Web lead waited 4 hours for a first response','Enquiry arrived 10:00am; first response 2:00pm. Hot leads cool fast in that window.','Call to qualify today — acknowledge the delay.',3400,'identified','medium','office',5, datetime('now','-5 days'), datetime('now','-5 days'), datetime('now','-5 days')),
('rop_8007','cmp_1000','slow_response','enq_7002','ldg_n2','Tom Garrison','ac_repair','Slow response','Urgent AC request answered after 4+ hours','Urgent enquiry sat 4h25m before first response during peak season.','Call immediately — lead is still unqualified.',8900,'identified','high','owner',3, datetime('now','-3 days'), datetime('now','-3 days'), datetime('now','-3 days')),
('rop_8008','cmp_1000','unworked_lead','ldg_c3','ldg_c3','Frank Moretti','installation','Unworked lead','$6,100 air-handler lead — second call still pending','Contacted once; voicemail 2 days ago; no second attempt recorded.','Second call attempt today — high-value job.',6100,'identified','medium','office',6, datetime('now','-2 days'), datetime('now','-6 days'), datetime('now','-2 days')),
('rop_8009','cmp_1000','booking_failure','ldg_ar1','ldg_ar1','Greg Palmer','furnace_replacement','Booking failure','Saturday visit requested — never confirmed','Customer asked for a specific day; confirmation still outstanding.','Confirm the Saturday slot with owner approval.',4850,'identified','high','office',3, datetime('now','-1 day'), datetime('now','-3 days'), datetime('now','-1 day')),
('rop_8010','cmp_1000','dormant_customer','ldg_d1','ldg_d1','Sarah Jenkins','boiler','Dormant customers','$9,200 boiler job — went quiet 45 days ago','Was ready to buy, then went silent. Budget cycles reset; a fresh specific offer reopens these.','Reactivation call — offer fall priority slot + financing.',9200,'identified','medium','owner',45, datetime('now','-45 days'), datetime('now','-1 day'), datetime('now','-1 day')),
('rop_8011','cmp_1000','dormant_customer','ldg_d2','ldg_d2','Omar Haddad','mini_split','Dormant customers','Dormant 38 days — sunroom ductless, season changed','Qualified in summer, postponed to fall. The season has now changed.','Season-check call with current lead times.',6800,'identified','medium','owner',38, datetime('now','-38 days'), datetime('now','-1 day'), datetime('now','-1 day')),
('rop_8012','cmp_1000','dormant_customer','ldg_d3','ldg_d3','Grace Liu','furnace_replacement','Dormant customers','Deferred for budget 52 days ago — financing unexplored','Deferred purely on budget; financing information was never sent.','Check-in call; lead with financing options.',5400,'identified','low','office',52, datetime('now','-52 days'), datetime('now','-1 day'), datetime('now','-1 day')),
('rop_8013','cmp_1000','dormant_customer','ldg_d4','ldg_d4','Nathan Price','heat_pump','Dormant customers','Waiting on rebate info for 60 days','Asked for utility-rebate details; nothing was sent.','Send rebate update, then call.',7600,'identified','medium','office',60, datetime('now','-60 days'), datetime('now','-1 day'), datetime('now','-1 day')),
('rop_8014','cmp_1000','handoff',NULL,'ldg_e3','Ellen Wiggins','maintenance','Human handoff','Owner call needed — $4,850 quote, customer waiting on tax refund','Sensitive timing: customer tied the purchase to her refund. Personal call, not automated.','Owner calls this week; do not send automated reminders.',4850,'identified','medium','owner',9, datetime('now','-9 days'), datetime('now','-2 days'), datetime('now','-2 days')),
('rop_8015','cmp_1000','quote','est_1003','ldg_e3','Ellen Wiggins','duct_repair','Quote follow-up','$4,850 duct-repair quote — follow-up due','Quote sent 5 days ago; first follow-up is due now.','Schedule the follow-up call for this week.',4850,'identified','medium','office',5, datetime('now','-5 days'), datetime('now','-5 days'), datetime('now','-5 days'));

-- Historical pipeline events — make the measured funnel honest (RECOVERED rows carry actual recovered_value)
INSERT INTO recovery_opportunities (id, company_id, source_type, source_id, lead_id, customer_name, job_type, category, title, why, recommended_action, estimated_value, stage, priority, owner, age_days, last_event_at, outcome_type, recovered_value, created_at, updated_at) VALUES
('rop_8101','cmp_1000','missed_call','mcl_4002','ldg_w2','Robert Hayes','furnace_replacement','Missed enquiry','Missed call recovered — $11,200 system replacement','After-hours call reached voicemail. Same-evening call-back booked the diagnostic.','Call back same evening.',11200,'recovered','high','owner',16, datetime('now','-6 days'),'appointment_booked', 11200, datetime('now','-16 days'), datetime('now','-6 days')),
('rop_8102','cmp_1000','missed_call','mcl_4003',NULL,'Carl Jensen','maintenance','Missed enquiry','Missed call recovered — maintenance plan signup','Daytime call missed during jobs; call-back converted to a plan.','Call back with maintenance-plan offer.',4800,'recovered','medium','owner',8, datetime('now','-7 days'),'appointment_booked', 4800, datetime('now','-8 days'), datetime('now','-7 days')),
('rop_8103','cmp_1000','quote','est_1004','ldg_w1','Monica Reyes','mini_split','Quote follow-up','$6,400 ductless quote — follow-up converted it','Quote answered on follow-up #2; deposit paid.','Second follow-up call.',6400,'recovered','medium','office',5, datetime('now','-1 day'),'quote_accepted', 6400, datetime('now','-5 days'), datetime('now','-1 day')),
('rop_8104','cmp_1000','quote',NULL,'ldg_l1','Charles Weaver','ac_repair','Quote follow-up','AC replacement quote — lost on price','Follow-up done; customer chose a competitor on price. Relationship preserved for next season.','One respectful final check-in.',3900,'lost','low','office',18, datetime('now','-8 days'),'lost_to_competitor', NULL, datetime('now','-18 days'), datetime('now','-8 days'));
